language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - mvn -B clean package
  - java -cp target/helloworld-1.0-SNAPSHOT.jar com.mycompany.app.App
